spring:
  profiles:
    active: dev
  http:
    encoding:
      force: true
entitymanager:
  packagesToScan: com.skylot.machine_boot
flyway:
  baseline-on-migrate: false
  encoding: utf8
  enabled: false
---
spring:
  profiles: pro
  datasource:
    url: jdbc:mysql://10.8.10.190:3306/fangda_skylot_mathinemgt_test_02?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: fangda
    password: 123456
logging:
  level: error